### ISSUE TITLE
Impossible to install on CentOS 6.5

### ISSUE THREAD

**Issue by pdonadeo** [areski/django-audiofield#7]
The installation instructions for CentOS as stated in README.rst are broken, because none of these four packages:

 * libsox-fmt-mp3
 * libsox-fmt-all
 * mpg321
 * dir2ogg

are present in the CentOS stock repositories, nor in EPEL.

**Comment by tylersavery** [comment]
Yes - I too am having no luck installing these dependencies on centos 6.5 - any help would be much appreciated!

**Comment by areski** [comment]
I'm not using CentOS, but if you know the packages needed please open a PR so that we can give some indication of what is needed
